name: Ejecutar script en Windows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"  # 12:00 PM Cuba
    - cron: "30 4 * * *"  # 11:30 PM Cuba

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install requests pytz pymongo

      - name: Ejecutar script
        run: python src/data_ingestion/up_to_date.py
